import type { NostrEvent } from '@nostrify/nostrify';
import { useNostr } from '@nostrify/react';
import { useQuery } from '@tanstack/react-query';

/** The actual RHR Nostr profile pubkey (rhr@primal.net / npub10uth...). */
export const RHR_PROFILE_PUBKEY = '7f177706ad6e0aea75a9e3345d9ffdae67676faff249be657b596375e1ced391';

/** The Primal LNURL nostrPubkey that signs zap receipts for rhr@primal.net. */
export const RHR_ZAP_RECEIPT_SIGNER_PUBKEY = 'f81611363554b64306467234d7396ec88455707633f54738f6c4683535098cd3';

/**
 * Include the legacy wallet pubkey because older invoices generated by this site
 * used it as the zap request's `p` tag. Normal Nostr clients zap the RHR
 * profile pubkey, while the receipt itself is signed by the LNURL provider.
 */
const RHR_ZAP_RECIPIENT_PUBKEYS = [RHR_PROFILE_PUBKEY, RHR_ZAP_RECEIPT_SIGNER_PUBKEY] as const;
const RHR_ZAP_RECIPIENT_SET = new Set<string>(RHR_ZAP_RECIPIENT_PUBKEYS);
const HEX_PUBKEY_RE = /^[0-9a-f]{64}$/;

export interface Supporter {
  pubkey: string;
  totalSats: number;
  latestAt: number;
}

/** Pubkeys excluded from the supporters list. */
const EXCLUDED_PUBKEYS = new Set<string>(RHR_ZAP_RECIPIENT_PUBKEYS);

function getZapSender(event: NostrEvent): string | null {
  // Try to parse the inner zap request first as it's the most reliable 
  // indicator of the *intended* sender (who signed the zap request)
  const descriptionTag = event.tags.find(([name]) => name === 'description')?.[1];
  if (descriptionTag) {
    try {
      const zapRequest = JSON.parse(descriptionTag);
      if (zapRequest.pubkey && HEX_PUBKEY_RE.test(zapRequest.pubkey)) {
        return zapRequest.pubkey;
      }
    } catch {
      // Invalid JSON
    }
  }

  // Fallback: NIP-57 zap receipts copy the sender into the uppercase P tag.
  const bigPTag = event.tags.find(([name]) => name === 'P')?.[1];
  if (bigPTag && HEX_PUBKEY_RE.test(bigPTag)) {
    return bigPTag;
  }

  return null;
}

function getZapRecipient(event: NostrEvent): string | null {
  const recipient = event.tags.find(([name, value]) => name === 'p' && value)?.[1];
  if (recipient && HEX_PUBKEY_RE.test(recipient)) {
    return recipient;
  }

  const descriptionTag = event.tags.find(([name]) => name === 'description')?.[1];
  if (descriptionTag) {
    try {
      const zapRequest = JSON.parse(descriptionTag);
      const requestRecipient = zapRequest.tags?.find((t: string[]) => t[0] === 'p')?.[1];
      if (requestRecipient && HEX_PUBKEY_RE.test(requestRecipient)) {
        return requestRecipient;
      }
    } catch {
      // Invalid JSON
    }
  }

  return null;
}

function getZapAmount(event: NostrEvent): number | null {
  // Extract Sats Amount:
  // Look for the amount tag (in millisats) and convert to sats.
  const amountTag = event.tags.find(([name]) => name === 'amount')?.[1];
  if (amountTag) {
    const msats = Number.parseInt(amountTag, 10);
    if (Number.isSafeInteger(msats) && msats > 0) {
      return Math.floor(msats / 1000);
    }
  }

  // Fallback 1: Parse the bolt11 tag string using regex match and multiply properly
  const bolt11 = event.tags.find(([name]) => name === 'bolt11')?.[1];
  if (bolt11) {
    return parseBolt11Amount(bolt11);
  }

  // Fallback 2: JSON.parse the description tag and find the amount tag within it
  const descriptionTag = event.tags.find(([name]) => name === 'description')?.[1];
  if (descriptionTag) {
    try {
      const zapRequest = JSON.parse(descriptionTag);
      const reqAmount = zapRequest.tags?.find((t: string[]) => t[0] === 'amount')?.[1];
      if (reqAmount) {
        const msats = Number.parseInt(reqAmount, 10);
        if (Number.isSafeInteger(msats) && msats > 0) {
          return Math.floor(msats / 1000);
        }
      }
    } catch {
      // Invalid JSON
    }
  }

  return null;
}

function parseBolt11Amount(bolt11: string): number | null {
  const lower = bolt11.toLowerCase();
  const match = lower.match(/^lnbc(\d+)([munp]?)/);
  if (!match) return null;

  const value = Number.parseInt(match[1], 10);
  if (!Number.isSafeInteger(value) || value <= 0) return null;

  const multiplier = match[2];
  switch (multiplier) {
    case 'm': return value * 100000;
    case 'u': return value * 100;
    case 'n': return Math.floor(value / 10);
    case 'p': return Math.floor(value / 10000);
    case '': return value * 100000000;
    default: return null;
  }
}

function aggregateZapSupporters(events: NostrEvent[]): Supporter[] {
  const map = new Map<string, { totalSats: number; latestAt: number }>();
  const seenZapIds = new Set<string>();

  for (const event of events) {
    if (event.kind !== 9735) continue;
    if (seenZapIds.has(event.id)) continue;
    seenZapIds.add(event.id);

    const recipient = getZapRecipient(event);
    if (!recipient || !RHR_ZAP_RECIPIENT_SET.has(recipient)) continue;

    const sats = getZapAmount(event);
    if (!sats || sats <= 0) continue;

    // A recipient could be zapping themselves, or zapping anonymously. 
    // If the sender cannot be identified via 'P' tag or description 
    // it was an anonymous zap - ignore it for the leaderboard.
    const sender = getZapSender(event);
    if (!sender) continue;
    if (EXCLUDED_PUBKEYS.has(sender)) continue;

    const existing = map.get(sender);
    if (existing) {
      existing.totalSats += sats;
      if (event.created_at > existing.latestAt) {
        existing.latestAt = event.created_at;
      }
    } else {
      map.set(sender, { totalSats: sats, latestAt: event.created_at });
    }
  }

  return Array.from(map.entries())
    .map(([pubkey, data]) => ({ pubkey, ...data }))
    .sort((a, b) => b.totalSats - a.totalSats);
}

const EXTRA_ZAP_RELAYS = [
  'wss://relay.primal.net',
  'wss://relay.damus.io',
  'wss://relay.ditto.pub',
  'wss://antiprimal.net',
];

export function useTopSupporters(limit: number = 10) {
  const { nostr } = useNostr();

  return useQuery<Supporter[]>({
    queryKey: ['top-supporters', RHR_PROFILE_PUBKEY],
    queryFn: async () => {
      const zapGroup = nostr.group(EXTRA_ZAP_RELAYS);
      const events = await zapGroup.query(
        RHR_ZAP_RECIPIENT_PUBKEYS.map((pubkey) => ({
          kinds: [9735],
          '#p': [pubkey],
          limit: 10000,
        })),
      );

      return aggregateZapSupporters(events).slice(0, limit);
    },
    staleTime: 60 * 1000,
    refetchInterval: 2 * 60 * 1000,
    retry: 1,
  });
}
